import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from 'react-query'
import { InternalApi } from '../services/internal-api'
import styles from '../styles/Home.module.css'
import { Input, Button } from 'antd';
import ReactCanvasConfetti from 'react-canvas-confetti'
import {
  HeartOutlined,
} from '@ant-design/icons';

const { Search } = Input;

const favouritePlaces = [
  'Wroclaw',
  'Wielun'
]

const canvasStyles: any = {
  position: 'fixed',
  pointerEvents: 'none',
  width: '100%',
  height: '100%',
  top: 0,
  left: 0
}

export default function Home() {
  const defaultPlace = favouritePlaces[0]
  const { data } = useQuery(`weather`, () => InternalApi.getWeather(defaultPlace));
  const [ savedPlaces ] = useState(favouritePlaces);
  const queryClient = useQueryClient();
  const { mutate } = useMutation(InternalApi.getWeather, {
    onSuccess: (data) => {
      console.log('DEBUGGING:  ~ file: index.tsx ~ line 26 ~ Home ~ data', data);
      queryClient.setQueryData('weather', data);
    }
  })
  const [fire, setFire] = useState(false);
  console.log('DEBUGGING:  ~ file: index.tsx ~ line 33 ~ Home ~ fire', fire);

  const [place, setPlace] = useState(defaultPlace)

  const onSearch = (value: string) => {
    mutate(value);
  }
  const onClickFav = (place: string) => () => {
    setPlace(place)
    mutate(place);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Handy-box</title>
        <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon-husky.png" />
      </Head>
      <main className={styles.main}>
          <img onClick={() => setFire(true)} style={{ height: '150px', marginTop: '50px'}} src="/logo-husky.png" alt="logo-husky">
          </img>
          <ReactCanvasConfetti className="canvas" fire={fire} style={canvasStyles}/>
        <h1 className={styles.title}>
          Welcome to handy-box!
        </h1>
        <p className={styles.description}>
          Create your place
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Weather</h2>
            <p>Saved places: </p>
            <ul>
              {savedPlaces.map(place => <li><Button icon={<HeartOutlined />} onClick={onClickFav(place)} name={place}>{place}</Button></li>)}
            </ul>
            <br />
            <Search placeholder="input search text" onSearch={onSearch} enterButton value={place} onChange={(e) => setPlace(e.target.value)}/>
            {data && (
              <div>
                <p>temp: {data.main.temp}</p>
                <p>temp_max: {data.main.temp_max}</p>
                <p>temp_min: {data.main.temp_min}</p>
                <p>feels_like: {data.main.feels_like}</p>
                <p>humidity: {data.main.humidity}</p>
                <p>pressure: {data.main.pressure}</p>
              </div>
            )
            }
          </div>
          <div className={styles.card}>
            <h2>Weather</h2>
          </div>
          <div className={styles.card}>
            <h2>Weather</h2>
          </div>
          <div className={styles.card}>
            <h2>Weather</h2>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
