import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import ReactCanvasConfetti from 'react-canvas-confetti'
import { WeatherCard } from '../components/weather/WeatherCard'


const canvasStyles: any = {
  position: 'fixed',
  pointerEvents: 'none',
  width: '100%',
  height: '100%',
  top: 0,
  left: 0
}

export default function Home() {
  const [fire, setFire] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Handy-box</title>
        <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon-husky.png" />
      </Head>
      <main className={styles.main}>
          <img onClick={() => setFire(true)} style={{ height: '150px', marginTop: '50px'}} src="/logo-husky.png" alt="logo-husky">
          </img>
          <ReactCanvasConfetti className="canvas" fire={fire} style={canvasStyles}/>
        <h1 className={styles.title}>
          Welcome to handy-box!
        </h1>
        <p className={styles.description}>
          Create your place
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <WeatherCard />
          </div>
          <div className={styles.card}>
            <h2>Reminder</h2>
          </div>
          <div className={styles.card}>
            <h2>Car</h2>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
